package com.wisesource.product.eddm.domain;

// Generated 2012-9-11 22:49:16 by Hibernate Tools 3.4.0.CR1

/**
 * TDbconnection generated by hbm2java
 */
public class TDbconnection implements java.io.Serializable {

	private String fconnid;
	private String fdriver;
	private String furl;
	private String fusername;
	private String fpassword;
	private String fname;

	public TDbconnection() {
	}

	public TDbconnection(String fconnid, String fname) {
		this.fconnid = fconnid;
		this.fname = fname;
	}

	public TDbconnection(String fconnid, String fdriver, String furl,
			String fusername, String fpassword, String fname) {
		this.fconnid = fconnid;
		this.fdriver = fdriver;
		this.furl = furl;
		this.fusername = fusername;
		this.fpassword = fpassword;
		this.fname = fname;
	}

	public String getFconnid() {
		return this.fconnid;
	}

	public void setFconnid(String fconnid) {
		this.fconnid = fconnid;
	}

	public String getFdriver() {
		return this.fdriver;
	}

	public void setFdriver(String fdriver) {
		this.fdriver = fdriver;
	}

	public String getFurl() {
		return this.furl;
	}

	public void setFurl(String furl) {
		this.furl = furl;
	}

	public String getFusername() {
		return this.fusername;
	}

	public void setFusername(String fusername) {
		this.fusername = fusername;
	}

	public String getFpassword() {
		return this.fpassword;
	}

	public void setFpassword(String fpassword) {
		this.fpassword = fpassword;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

}
