package com.wisesource.product.eddm.domain;

// Generated 2012-9-11 22:49:16 by Hibernate Tools 3.4.0.CR1

/**
 * TMytask generated by hbm2java
 */
public class TMytask implements java.io.Serializable {

	private String ftaskid;

	public TMytask() {
	}

	public TMytask(String ftaskid) {
		this.ftaskid = ftaskid;
	}

	public String getFtaskid() {
		return this.ftaskid;
	}

	public void setFtaskid(String ftaskid) {
		this.ftaskid = ftaskid;
	}

}
