package com.wisesource.product.eddm.domain;

// Generated 2012-9-11 22:49:16 by Hibernate Tools 3.4.0.CR1

/**
 * TProcessDbconn generated by hbm2java
 */
public class TProcessDbconn implements java.io.Serializable {

	private TProcessDbconnId id;

	public TProcessDbconn() {
	}

	public TProcessDbconn(TProcessDbconnId id) {
		this.id = id;
	}

	public TProcessDbconnId getId() {
		return this.id;
	}

	public void setId(TProcessDbconnId id) {
		this.id = id;
	}

}
