package com.wisesource.product.eddm.domain;

// Generated 2012-9-11 22:49:16 by Hibernate Tools 3.4.0.CR1

/**
 * TProcess generated by hbm2java
 */
public class TProcess implements java.io.Serializable {

	private String fprocessid;
	private String fworkid;

	public TProcess() {
	}

	public TProcess(String fprocessid, String fworkid) {
		this.fprocessid = fprocessid;
		this.fworkid = fworkid;
	}

	public String getFprocessid() {
		return this.fprocessid;
	}

	public void setFprocessid(String fprocessid) {
		this.fprocessid = fprocessid;
	}

	public String getFworkid() {
		return this.fworkid;
	}

	public void setFworkid(String fworkid) {
		this.fworkid = fworkid;
	}

}
