package com.wisesource.product.eddm.domain;

// Generated 2012-9-11 22:49:16 by Hibernate Tools 3.4.0.CR1

/**
 * TProcessDo generated by hbm2java
 */
public class TProcessDo implements java.io.Serializable {

	private String fdoid;
	private String fprocessid;
	private String flag;

	public TProcessDo() {
	}

	public TProcessDo(String fdoid, String fprocessid) {
		this.fdoid = fdoid;
		this.fprocessid = fprocessid;
	}

	public TProcessDo(String fdoid, String fprocessid, String flag) {
		this.fdoid = fdoid;
		this.fprocessid = fprocessid;
		this.flag = flag;
	}

	public String getFdoid() {
		return this.fdoid;
	}

	public void setFdoid(String fdoid) {
		this.fdoid = fdoid;
	}

	public String getFprocessid() {
		return this.fprocessid;
	}

	public void setFprocessid(String fprocessid) {
		this.fprocessid = fprocessid;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
