package com.wisesource.product.eddm.domain;

// Generated 2012-9-11 22:49:16 by Hibernate Tools 3.4.0.CR1

/**
 * TWork generated by hbm2java
 */
public class TWork implements java.io.Serializable {

	private String fworkid;
	private String ftaskid;
	private String fpworkid;
	private String datasource;
	private String fworkname;
	private String keys;
	private String fsql;
	private String fprocessid;
	private String foreignkey;

	public TWork() {
	}

	public TWork(String fworkid) {
		this.fworkid = fworkid;
	}

	public TWork(String fworkid, String ftaskid, String fpworkid,
			String datasource, String fworkname, String keys, String fsql,
			String fprocessid, String foreignkey) {
		this.fworkid = fworkid;
		this.ftaskid = ftaskid;
		this.fpworkid = fpworkid;
		this.datasource = datasource;
		this.fworkname = fworkname;
		this.keys = keys;
		this.fsql = fsql;
		this.fprocessid = fprocessid;
		this.foreignkey = foreignkey;
	}

	public String getFworkid() {
		return this.fworkid;
	}

	public void setFworkid(String fworkid) {
		this.fworkid = fworkid;
	}

	public String getFtaskid() {
		return this.ftaskid;
	}

	public void setFtaskid(String ftaskid) {
		this.ftaskid = ftaskid;
	}

	public String getFpworkid() {
		return this.fpworkid;
	}

	public void setFpworkid(String fpworkid) {
		this.fpworkid = fpworkid;
	}

	public String getDatasource() {
		return this.datasource;
	}

	public void setDatasource(String datasource) {
		this.datasource = datasource;
	}

	public String getFworkname() {
		return this.fworkname;
	}

	public void setFworkname(String fworkname) {
		this.fworkname = fworkname;
	}

	public String getKeys() {
		return this.keys;
	}

	public void setKeys(String keys) {
		this.keys = keys;
	}

	public String getFsql() {
		return this.fsql;
	}

	public void setFsql(String fsql) {
		this.fsql = fsql;
	}

	public String getFprocessid() {
		return this.fprocessid;
	}

	public void setFprocessid(String fprocessid) {
		this.fprocessid = fprocessid;
	}

	public String getForeignkey() {
		return this.foreignkey;
	}

	public void setForeignkey(String foreignkey) {
		this.foreignkey = foreignkey;
	}

}
